server:
  port: 8085

spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER
          predicates:
            - Path=/users/**

        - id: product-service
          uri: lb://PRODUCT
          predicates:
            - Path=/product/**

        - id: cart-service
          uri: lb://CART
          predicates:
            - Path=/cart/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
